version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vtat2011
      MYSQL_DATABASE: product

  spring-boot-app:
    build:
      context: .                 # trỏ tới thư mục gốc
      dockerfile: ./src/Dockerfile  # trỏ đến file Dockerfile trong src/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/testflutter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vtat2011

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
